# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-06-22 04:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveIntegerField(choices=[(0, 'Group'), (1, 'Knock out')])),
                ('date', models.DateTimeField(null=True)),
                ('home_result', models.PositiveIntegerField(blank=True, null=True)),
                ('away_result', models.PositiveIntegerField(blank=True, null=True)),
                ('home_penalty', models.PositiveIntegerField(blank=True, null=True)),
                ('away_penalty', models.PositiveIntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('rare_coef', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_result_predict', models.PositiveIntegerField()),
                ('away_result_predict', models.PositiveIntegerField()),
                ('home_penalty_predict', models.PositiveIntegerField(blank=True, null=True)),
                ('away_penalty_predict', models.PositiveIntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pishi.Match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('num_predicted', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveIntegerField()),
                ('fifa_code', models.CharField(max_length=10, null=True)),
                ('iso2', models.CharField(max_length=3, null=True)),
                ('flag', models.URLField(null=True)),
                ('emoji', models.CharField(max_length=20, null=True)),
                ('emoji_string', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='predict',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pishi.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='pishi.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='pishi.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pishi.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='predict',
            unique_together=set([('user', 'match')]),
        ),
    ]
